
POST http://localhost:8080/Listener HTTP/1.1
content-type: application/json

{
    "name": "jay2",
    "bindPort": "8001"
}

### 
GET http://localhost:8080/Listeners HTTP/1.1
### 
GET http://localhost:8080/Listeners/danny HTTP/1.1
### 
DELETE http://localhost:8080/StopListener/jay HTTP/1.1

### 
GET http://localhost:8080/Agents HTTP/1.1
### 
POST http://localhost:8080/GenerateAgent HTTP/1.1
content-type: application/json

{
    "os": "windows",
    "arch": "amd64"
}